// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0bry7PGR_XedChDMhx2BeIhy1t-u8SrA',
    appId: '1:770853212778:web:285aa8c0e373b0cbe7f013',
    messagingSenderId: '770853212778',
    projectId: 'shophub-48c54',
    authDomain: 'shophub-48c54.firebaseapp.com',
    storageBucket: 'shophub-48c54.firebasestorage.app',
    measurementId: 'G-YS8HMXZDHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-K_LCJZgxISrvsf29Qqcrpmdjw7B3ves',
    appId: '1:770853212778:android:e84fd679e5cf4c67e7f013',
    messagingSenderId: '770853212778',
    projectId: 'shophub-48c54',
    storageBucket: 'shophub-48c54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu_iDK_dlzn0K81ULybMsJkhUmTL9Tp_s',
    appId: '1:770853212778:ios:2d1c04166505fb1ee7f013',
    messagingSenderId: '770853212778',
    projectId: 'shophub-48c54',
    storageBucket: 'shophub-48c54.firebasestorage.app',
    iosBundleId: 'com.example.shopHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu_iDK_dlzn0K81ULybMsJkhUmTL9Tp_s',
    appId: '1:770853212778:ios:2d1c04166505fb1ee7f013',
    messagingSenderId: '770853212778',
    projectId: 'shophub-48c54',
    storageBucket: 'shophub-48c54.firebasestorage.app',
    iosBundleId: 'com.example.shopHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0bry7PGR_XedChDMhx2BeIhy1t-u8SrA',
    appId: '1:770853212778:web:58c7d4a2be6325a1e7f013',
    messagingSenderId: '770853212778',
    projectId: 'shophub-48c54',
    authDomain: 'shophub-48c54.firebaseapp.com',
    storageBucket: 'shophub-48c54.firebasestorage.app',
    measurementId: 'G-TVK1DJGYH7',
  );
}
